package counter 

// list of common words
var CommonWords = map[string]struct{}{
	"is":     {},
	"and":    {},
	"an":     {},
	"the":    {},
	"by":     {},
	"to":     {},
	"of":     {},
	"a":      {},
	"at":     {},
	"for":    {},
	"it":     {},
	"in":     {},
	"from":   {},
	"this":   {},
	"that":   {},
	"or":     {},
	"on":     {},
	"with":   {},
	"then":   {},
	"than":   {},
	"these":  {},
	"our":    {},
	"your":   {},
	"more":   {},
	"less":   {},
	"most":   {},
	"who":    {},
	"has":    {},
	"have":   {},
	"will":   {},
	"be":     {},
	"you're":     {},
	"we":     {},
	"are":     {},
}